### ISSUE TITLE
Server VM: "Error communicating to the Forseti server."

### ISSUE THREAD

**Issue by choonchernlim** [forseti-security/terraform-google-forseti#468]
When I run the following command: `forseti model delete test-model` in the server VM, I get this error:-

```
Error communicating to the Forseti server.
Please check the status of the server and make sure it's running.
If you are accessing from a client VM, make sure the `server_ip` field 
inside the client configuration file in the Forseti client GCS bucket 
contains the right IP address.
```

When I go to `/var/log/syslog`, I see this error message: `Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.` 

I'm using a shielded VM (`gce-uefi-images/ubuntu-1804-lts`) if that makes any difference.

How do I go about troubleshooting/fixing this problem?

Thank you.

**Comment by gkowalski-google** [comment]
Hi @choonchernlim, if you are getting that error on the Forseti server then it seems likely that the Forseti service is not running. Can you check the Stackdriver logs for the server VM and look for any errors? You can also try searching for `forseti startup` to see where in the startup script things went awry.

The NXDOMAIN message can be ignored, that is coming Ubuntu and should not be causing any issues for Forseti.

I'm not sure if we have tested Forseti on that machine type. Just curious why you chose that type, is there some benefit for using that over the default `ubuntu-os-cloud/ubuntu-1804-lts`?

**Comment by choonchernlim** [comment]
I'm going to try to comb through the log file for errors later. 

My institution requires the Forseti instance to be spun up using a shielded VM. Is there a recommended shielded VM image I should be using instead of `gce-uefi-images/ubuntu-1804-lts`?

**Comment by xingao267** [comment]
I've tested on that machine type, so I don't think the machine type is the issue. Usually I see this kind of error when the server VM is not fully ready (in a short period after startup). But Mike and I communicated offline, and that seems not the cause either.

**Comment by choonchernlim** [comment]
After trying several things for 2 to 3 hours here, I can consistently get  `forseti model delete test-model` to work in server VM if I either do a `reset` on the VM or `reset` immediately followed by `stop` then `restart`. @xingao267 did mention the same thing to me on how he fixes this error himself.

There are no pressing errors that jump out from the Stackdriver logs, and I always waited until I see "Startup finished in XXs (kernel) + XXs (userspace) = XXs" message before I ssh in to test the command.

My next step is to see if I'm seeing the same behavior on the default regular VM or not.

Is there a command that I can run manually in server VM to start the Forseti server/service?

Thank you.

**Comment by gkowalski-google** [comment]
Sorry to hear that @choonchernlim, agree it doesn't seem like a machine type issue, but curious to know if you see the same behavior.

You can start the Forseti service like this `sudo systemctl start forseti`. It seems like the service is stopping, so next time you see it not working, but be worthwhile to try `sudo systemctl status forseti` to see if that gives you any messages about why it stopped.

**Comment by choonchernlim** [comment]
When I run `sudo systemctl start forseti`, I get this error: `Failed to start forseti.service: Unit forseti.service not found.`. How do I go about troubleshooting this?

By the way, is it possible to have 2 Forseti instances running under the same org and with both instances connecting to CSCC?

**Comment by choonchernlim** [comment]
By the way, I tried the default non-shielded VM last night, and it produced the same error. I verified that the server VM can ping externally.

**Comment by xingao267** [comment]
https://github.com/forseti-security/forseti-security/issues/3615 and https://github.com/forseti-security/forseti-security/pull/3616 might be related. It's likely due to the module but due to a bug in the forseti startup script which cause your instance not started properly.

@hshin-g is there a way to pin to stable version of Forseti installer or startup script this this kind of issue does not happen? Because other Forseti instances I deployed before does not have this issue, and this bug seems introduced only very recently. And in the terraform module, we pinned to Forseti v2.24.0, and I thought that should give us a deterministic Forseti installer.

**Comment by choonchernlim** [comment]
Now that Forseti v2.24.1 is out, I tried pinning that version:-

```
module "forseti" {
  source           = "..."
  ...
  forseti_version  = "v2.24.1"
}
```

... then `destroy`, `apply` and waited for the startup script to complete. 

I still get `Unit forseti.service not found` when I run `sudo systemctl status forseti`.

Are there any additional steps I need to take after provisioning it before I check whether the Forseti service is running in the server VM?

Thanks.

**Comment by hshin-g** [comment]
@choonchernlim We discovered that there were some backwards incompatible changes from the master branch that were merged into the v5.1.1 release of the Terraform module. We have deleted and recreated the right v5.1.1 release- can you try running `terraform init` with `version = "~>5.1"` (and `forseti_version="v2.24.0" i.e. the default) to pull down the correct changes and run `terraform apply` and see if that solves the issue?

**Comment by choonchernlim** [comment]
@hshin-g No dice. I re-downloaded v5.1.1 with no `forseti_version` defined, then did a `destroy` and `apply`... and I still see this error in the server VM:-

```
$ sudo systemctl status forseti
Unit forseti.service could not be found.
```

When I scan through the Stackdriver log, should the startup script returns code 0 or code 1? Right now, I'm seeing this:-
```
startup-script: INFO startup-script: Return code 1. 
```

If it helps at all, here's my Forseti configuration (tested by @xingao267)... I'm using the default VM instead of shielded VM for now to troubleshoot this problem.
```
module "forseti" {
  source                             = "../modules/forseti-5.1.1"
  domain                             = local.domain
  project_id                         = local.project_id
  org_id                             = local.org_id
  cscc_violations_enabled            = true
  cscc_source_id                     = local.cscc_source_id
  composite_root_resources           = ["organizations/${local.org_id}"]
  manage_rules_enabled               = false
  instance_network_interface_enabled = true
  lien_enabled                       = false
  config_validator_enabled           = true
  server_private                     = true
  client_private                     = true
  cloudsql_private                   = true
  server_region                      = local.region
  client_region                      = local.region
  cloudsql_region                    = local.region
  storage_bucket_location            = local.region
  bucket_cai_location                = local.region
  network                            = local.network
  subnetwork                         = local.subnetwork
}
```

Thank you.

**Comment by hshin-g** [comment]
Thanks for the info @choonchernlim. Where is the source `"../modules/forseti-5.1.1"` coming from? Are you utilizing the v5.1.1 tag found here: https://registry.terraform.io/modules/terraform-google-modules/forseti/google/5.1.1.

Can you try running `sudo systemctl restart forseti` and see if that gets the application running?

**Comment by choonchernlim** [comment]
I downloaded the zip file from https://github.com/forseti-security/terraform-google-forseti/releases/tag/v5.1.1 ... updated an hour ago. I can try pulling from the registry if you feel the codebase is different.

```
$ sudo systemctl restart forseti
Failed to restart forseti.service: Unit forseti.service not found.
```

**Comment by hshin-g** [comment]
Can you check in the Serial Port 1 (Console) logs (navigate to your Server VM in the console and there should be a list under Logs) and see if there is an output of`INFO Finished running startup scripts.`? It takes a while after the VM is created since there are packages, etc. that are downloaded/installed. Once you see that output, can you try running `sudo systemctl restart forseti` again?

**Comment by choonchernlim** [comment]
Yes, I can confirm that output message exists.
```
Jan 31 19:22:43 forseti-server-vm-f81fd8bc startup-script: INFO Finished running startup scripts.
Jan 31 19:22:43 forseti-server-vm-f81fd8bc systemd[1]: Started Google Compute Engine Startup Scripts.
Jan 31 19:22:43 forseti-server-vm-f81fd8bc systemd[1]: Startup finished in 4.367s (kernel) + 38.129s (userspace) = 42.496s.
```

Running that command yields the same error message.


I further scanned through Serial Port 1 (Console) logs... and here's what I see:-

**warning**
```
Warning: fsck not present, so sk[    4.099038] EXT4-fs (sda1): INFO: recovery required on readonly filesystem
Jan 31 19:22:11 forseti-server-vm-f81fd8bc kernel: [    1.788549] i8042: Warning: Keylock active
[    1.788549] i8042: Warning: Keylock active
```

**error**
```
[    1.848466] RAS: Correctable Errors collector initialized.
Jan 31 19:22:11 forseti-server-vm-f81fd8bc kernel: [    1.848466] RAS: Correctable Errors collector initialized.
Jan 31 19:22:11 forseti-server-vm-f81fd8bc systemd-resolved[978]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 31 19:22:11 forseti-server-vm-f81fd8bc systemd-resolved[978]: message repeated 7 times: [ Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.]
Jan 31 19:22:22 forseti-server-vm-f81fd8bc systemd-resolved[978]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 31 19:22:22 forseti-server-vm-f81fd8bc systemd-resolved[978]: message repeated 2 times: [ Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.]
```

**fatal**
```
Jan 31 19:22:43 forseti-server-vm-f81fd8bc startup-script: INFO startup-script: fatal: destination path 'forseti-security' already exists and is not an empty directory.
```

**Comment by hshin-g** [comment]
When you did `terraform destroy` the first time, did you ensure that all resources were destroyed properly before running `terraform init` and then `terraform apply` for the new v5.1.1 tag?

If it's possible, can you try creating a new project and redeploying using this walkthrough tutorial: https://console.cloud.google.com/cloudshell/open?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fforseti-security%2Fterraform-google-forseti.git&cloudshell_git_branch=modulerelease511&cloudshell_working_dir=examples/install_simple&cloudshell_image=gcr.io%2Fgraphite-cloud-shell-images%2Fterraform%3Alatest&cloudshell_tutorial=.%2Ftutorial.md? Just trying to see where in the process this all is happening.

**Comment by choonchernlim** [comment]
Yes, I'm pretty certain that all the resources were properly destroyed before I `apply` it again.

I'll do the walkthrough tutorial now.

By the way, I don't believe I got this question answered (got buried above) but... 

The org that I'm currently in already has a Forseti instance running and it is connected to CSCC (@xingao267 helped me with that). Do you think that this problem is due to the fact that I'm trying to spin up another Forseti instance and attempting to connect to CSCC in the same org?

**Comment by xingao267** [comment]
I was able to run two forseti project/instance in the same org before. But didn't try connecting the second one to CSCC (might not even possible because you can only input one server service account in the CSCC Forseti connector, I'm still trying). You can remove 
cscc_source_id                     = local.cscc_source_id
and set enable cscc to false to eliminate that variable.

**Comment by xingao267** [comment]
I think I found something promising...

There is this error:
Jan 31 19:48:17 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: Finished processing dependencies for forseti-security==2.24.0
Jan 31 19:48:17 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: Forseti Startup - Downloading Forseti configuration from GCS.
Jan 31 19:48:18 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: Copying gs://forseti-server-9aecc8b2/configs/forseti_conf_server.yaml...
Jan 31 19:48:18 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: / [0 files][    0.0 B/ 19.8 KiB]                                                #015/ [1 files][ 19.8 KiB/ 19.8 KiB]
Jan 31 19:48:18 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: Operation completed over 1 objects/19.8 KiB.
Jan 31 19:48:19 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: CommandException: No URLs matched: gs://forseti-server-9aecc8b2/rules
Jan 31 19:48:20 forseti-server-vm-9aecc8b2 startup-script: INFO startup-script: Return code 1.
Jan 31 19:48:20 forseti-server-vm-9aecc8b2 startup-script: INFO Finished running startup scripts.

And I guess this happens when you set `manage_rules_enabled` to `false` in the module invocation.

This is an existing bug, and was not discovered before because although I set it to `false`, BUT I upload my own versions of rules right after I deployed Forseti, so the specific path was able to be found by the startup script. But @choonchernlim probably didn't do that, and the start up script just stuck there.

I uploaded the rules, and reset the VMs. Will report back here if this is indeed the issue.

**Comment by xingao267** [comment]
So when `manage_rules_enabled` is `false`, either the module itself should create an empty folder in the server bucket, or the startup script should not try to download the rules.

**Comment by choonchernlim** [comment]
Here's the update... 

When I followed the walkthrough tutorial, the service started successfully.

When I pasted my above configuration into the walkthrough code and did a `destroy` and `apply`, the problem came back.

I'm going to try with `manage_rules_enabled` set to `true` to see if the problem goes away.

**Comment by xingao267** [comment]
I can confirm that with Forseti Terraform module v5.1.0 + Forseti v2.24.0 + `manage_rules_enabled` to `false` + my local change to use shielded VM, it works if I upload both legacy rules and policy library constraints to the bucket before the startup script finishes :) or reset VM after they are uploaded.

**Comment by choonchernlim** [comment]
I can also confirm that if `manage_rules_enabled` is set to `false`, the service will not start in the server VM. This looks like a bug to me.

Also, I'm seeing a lot of SQL-related errors in the log. Is this normal?

<img width="1628" alt="Screen Shot 2020-01-31 at 5 33 31 PM" src="https://user-images.githubusercontent.com/6835135/73581839-42fa6500-4450-11ea-9c0a-464b02311422.png">
 
Finally, #440 is worth fixing, at least for me since I have been rerunning this module more than 50 times now. :) I can't really do a clean `destroy` due to this error.

**Comment by choonchernlim** [comment]
There are still some finickiness with this, which I'm still trying to figure out the root cause of the problem.

So, the problem stemmed from the fact that `manage_rules_enabled` is set to `false`.

After manually pushing the rules to the GCS bucket, I do a `reset` to rebuild the server VM.

When SSH into server, sometimes it works flawlessly.

Other times, I get into this problem below:-

* `sudo systemctl status forseti` returns the following output:-

```
● forseti.service - Forseti API Server
   Loaded: loaded (/lib/systemd/system/forseti.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```
   
* So, I run `sudo systemctl restart forseti`.
   
* Now, `sudo systemctl status forseti` seems to show the service is running:-

```
● forseti.service - Forseti API Server
   Loaded: loaded (/lib/systemd/system/forseti.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-02-01 17:57:17 UTC; 1min 1s ago
 Main PID: 5141 (forseti_server)
    Tasks: 12 (limit: 4915)
   CGroup: /system.slice/forseti.service
           └─5141 /usr/bin/python3 /usr/local/bin/forseti_server --endpoint [::]:50051 --forseti_db mysql+pymysql://root@127.0.0.1:3306/forseti_security?c
```
   
* But when I run `forseti model delete test-model`, I get this error message back:-
   
```
Error communicating to the Forseti server.
Please check the status of the server and make sure it's running.
If you are accessing from a client VM, make sure the `server_ip` field inside the client configuration file in the Forseti client GCS bucket contains the right IP address.
```

When I check the Serial Port 1 (Console) logs, I see this:-

```
Feb  1 17:58:25 forseti-server-vm-8ec4bb75 cloud_sql_proxy[4099]: 2020/02/01 17:58:25 New connection for "mike-forseti-266903:us-central1:forseti-server-db-8ec4bb75"
Feb  1 17:59:28 forseti-server-vm-8ec4bb75 cloud_sql_proxy[4099]: 2020/02/01 17:59:28 couldn't connect to "mike-forseti-266903:us-central1:forseti-server-db-8ec4bb75": dial tcp 10.65.0.3:3307: connect: connection timed out
```

Last night, when I replayed the `destroy` and `apply` steps twice, it worked fine.

This AM, I get this error from the same codebase.  I'm going to try to `destroy` and `apply` again to see if the problem goes away.

**Comment by choonchernlim** [comment]
To prove how finicky it is, when I perform a `destroy` and `apply` again.

When I ssh into the server VM to check the service and perform a simple `forseti model delete test-model`, it failed, and the error log shows DB connectivity problem:-  

```
Feb  1 18:41:53 forseti-server-vm-5d5c5254 cloud_sql_proxy[3907]: 2020/02/01 18:41:53 Listening on 127.0.0.1:3306 for mike-forseti-266903:us-central1:forseti-server-db-5d5c5254
Feb  1 18:41:53 forseti-server-vm-5d5c5254 cloud_sql_proxy[3907]: 2020/02/01 18:41:53 Ready for new connections
Feb  1 18:41:57 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Forseti Startup - Attempting to update database schema, if necessary.
Feb  1 18:41:58 forseti-server-vm-5d5c5254 cloud_sql_proxy[3907]: 2020/02/01 18:41:58 New connection for "mike-forseti-266903:us-central1:forseti-server-db-5d5c5254"
Feb  1 18:42:30 forseti-server-vm-5d5c5254 cloud_sql_proxy[3907]: 2020/02/01 18:42:30 couldn't connect to "mike-forseti-266903:us-central1:forseti-server-db-5d5c5254": dial tcp 10.159.0.3:3307: connect: connection timed out
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: ['/home/ubuntu/forseti-security/install/gcp/upgrade_tools/db_migrator.py']
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Traceback (most recent call last):
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script:   File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script:     return fn()
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script:   File "/home/ubuntu/forseti-security/.eggs/SQLAlchemy-1.2.18-py3.6-linux-x86_64.egg/sqlalchemy/pool.py", line 425, in connect
... // more tracktrace
... // more tracktrace
... // more tracktrace
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script:     CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') (Background on this error at: http://sqlalche.me/e/e3q8)
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Return code 1.
Feb  1 18:42:30 forseti-server-vm-5d5c5254 startup-script: INFO Finished running startup scripts.
Feb  1 18:42:30 forseti-server-vm-5d5c5254 systemd[1]: Started Google Compute Engine Startup Scripts.
Feb  1 18:42:30 forseti-server-vm-5d5c5254 systemd[1]: Startup finished in 4.424s (kernel) + 2min 19.306s (userspace) = 2min 23.730s.
```

Then, I performed a `reset` on the server VM, and it works successfully with the log showing this:-

```
Feb  1 18:47:27 forseti-server-vm-5d5c5254 cloud_sql_proxy[4079]: 2020/02/01 18:47:27 Rlimits for file descriptors set to {&{8500 8500}}
Feb  1 18:47:29 forseti-server-vm-5d5c5254 cloud_sql_proxy[4079]: 2020/02/01 18:47:29 Listening on 127.0.0.1:3306 for mike-forseti-266903:us-central1:forseti-server[[0;32m  OK  [0m] Started Google Compute Engine Startup Scripts.
-db-5d5c5254
Feb  1 18:47:29 forseti-server-vm-5d5c5254 cloud_sql_proxy[4079]: 2020/02/01 18:47:29 Ready for new connections
Feb  1 18:47:32 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Forseti Startup - Attempting to update database schema, if necessary.
Feb  1 18:47:33 forseti-server-vm-5d5c5254 cloud_sql_proxy[4079]: 2020/02/01 18:47:33 New connection for "mike-forseti-266903:us-central1:forseti-server-db-5d5c5254"
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: ['/home/ubuntu/forseti-security/install/gcp/upgrade_tools/db_migrator.py']
Feb  1 18:47:34 forseti-server-vm-5d5c5254 cloud_sql_proxy[4079]: 2020/02/01 18:47:34 Client closed local connection on 127.0.0.1:3306
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Forseti Startup - Enabling and starting Forseti service.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 systemd[1]: Reloading.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Created symlink /etc/systemd/system/multi-user.target.wants/forseti.service → /lib/systemd/system/forseti.service.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 systemd[1]: Started Forseti API Server.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Forseti Startup - Success! The Forseti API server has been enabled and started.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Forseti Startup - Added the run_forseti.sh to crontab under user ubuntu.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Forseti Startup - Execution of startup script finished.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO startup-script: Return code 0.
Feb  1 18:47:34 forseti-server-vm-5d5c5254 startup-script: INFO Finished running startup scripts.
Feb  1 18:47:35 forseti-server-vm-5d5c5254 systemd[1]: Started Google Compute Engine Startup Scripts.
Feb  1 18:47:35 forseti-server-vm-5d5c5254 cloud_sql_proxy[4079]: 2020/02/01 18:47:35 New connection for "mike-forseti-266903:us-central1:forseti-server-db-5d5c5254"
Feb  1 18:47:35 forseti-server-vm-5d5c5254 systemd[1]: Startup finished in 4.451s (kernel) + 1min 44.538s (userspace) = 1min 48.990s.
Equivalent command line
```

I understand this Forseti module is complex, but the Terraform replayability seems suspicious here... given the same codebase/configuration from my end, sometimes it works, other times it doesn't.

**Comment by choonchernlim** [comment]
@xingao267 , @gkowalski-google  and @hshin-g ... thank you very much for your help. 

For now, I can live with the slight quirkiness. I feel https://github.com/forseti-security/terraform-google-forseti/issues/468#issuecomment-580886910 mentioned by @xingao267 needs to be addressed to ensure it won't just break the service startup if `manage_rules_enabled` is set to  `false`.

I'm going to go ahead and close this issue.
